version: '2'

services:
  web:
    build: web/
    volumes:
      - ./web:/usr/local/src/
      - rubygems:/usr/local/bundle
    external_links:
      - postgres
    command: bundle exec rails s -p 3333 -b '0.0.0.0'
    stdin_open: true
    tty: true
    ports:
      - "3333:3333"

  postgres:
    image: postgres:9.5.2
    working_dir: /root/db
    volumes:
      - ./db:/root/db
    environment:
      - PGDATABASE=hapi
      - PGHOST=postgres
      - PGUSER=postgres

volumes:
  rubygems:
    driver: local

